export const table: string;
export const extendOnBorders: string;
export const right: string;
export const center: string;
export const left: string;
export const trHighlighted: string;
export const clickable: string;
export const scrollable: string;
export const hideOnMobile: string;
