export const panel: string;
export const header: string;
export const details: string;
export const assets: string;
export const errors: string;
export const topLeftCorner: string;
export const assetPicker: string;
export const swapIcon: string;
export const input: string;
