export const select: string;
export const wrapperBordered: string;
export const wrapper: string;
export const disabled: string;
export const xs: string;
export const sm: string;
export const md: string;
export const lg: string;
export const unsized: string;
