export const container: string;
export const orderTypeBtn: string;
export const right: string;
export const myTradesTable: string;
export const myOpenTradesTable: string;
export const myCloseTradesTable: string;
export const status: string;
export const statusText: string;
export const statusProgress: string;
