export const main: string;
export const block: string;
export const title: string;
export const close: string;
export const icon: string;
export const iconInner: string;
export const description: string;
export const link: string;
export const cross: string;
